### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ClassickTech** [movie-web/movie-web#416] opened 2023-08-28 22:20 UTC
### What happened?

Working hosts were somehow borked for self hosters on the releases after 3.0.15. 

The self host guide works for 3.0.15 and earlier. Not for any release afterwards.

I compared that version and the latest version 3.2.1 and I think the culprit is somewhere in the index-a5d2672e.js file. It's either that, or the self host guide needs to be updated. 

### What browsers are you seeing the problem on?

Firefox, Chrome

### Other relevant information

Same exact issue as here. https://github.com/movie-web/movie-web/issues/382

**Comment by zisra** [comment] 2023-08-28 22:24
What errors are you seeing in the console?

**Comment by mrjvs** [comment] 2023-08-28 22:31
I have just setup a selfhosted instance to test on the latest version (following the guide). Everything works as expected.
Your selfhosted instance must be misconfigured.

Since 3.0.15, a new configuration option was added. double check that you have all of it setup correctly.

You can try reading the selfhosting guide again and refollowing all steps.
We don't provide any further support for selfhosted instances, as stated as first line in the selfhosting guide.

closing, cant reproduce

**Closed by mrjvs** 2023-08-28 22:31 UTC
Labels: bug, awaiting-approval

**Comment by ClassickTech** [comment] 2023-08-28 22:39
I have read that guide up and down at least 20 times. lol. Like i said, I configured it the same exact way the guide has it for 3.0.15 and it works great. Cloudflare script + Netlify. Any release after that, it doesn't. I have seen a people on here and in the discord have the same issue. I know you don't support self host but I was just hoping you'd update the bug.

**Comment by mrjvs** [comment] 2023-08-28 22:53
As I've set up an instance myself just now with working sources. I dont think this is a bug.

---

If only sources dont work and search works fine, it must be the cloudflare worker being misconfigured or wrong worker url

If search also doesn't work, it's the tmdb api key that's not working.

Superstream hasn't been changed in forever, there is no reason that would stop working with an update without misconfiguration.

Try clearing cache of your browser and using a different browser to see if that changes anything, if it does then the PWA cache doesn't update correctly (which is a bug)

After failing a source, the exact error with the runner context is logged. You can try looking at those errors to see if it's something you can solve with configuration.

---

Those are some steps you can take to investigate. But as I said, I dont think this is a bug, rather user error. Especially since the main deployment, test deployments and all contributer local setups all use the same method of hosting. Same method as selfhosters, which we have around 125 of.

**Comment by ClassickTech** [comment] 2023-08-28 23:03
Yea, I've tried different browsers, resetting cache and all that. I know it's not the tmdb key because it works on 3.0.15. I know it's not the cloudflare script (workers.js  v0.0.6) , because it works on 3.0.15.  I used winmerge to compare 3.0.15 and 3.2.1 and the only major differences between the 2 folders is the  index-a5d2672e.js file. So there's something that changed and broke it for me and whoever else is getting this same problem, like this guy here https://github.com/movie-web/movie-web/issues/382, Anyways, I know u don't like to support self host but I am hoping maybe if someone else is having this issue then they can chime in and help me.

**Comment by mrjvs** [comment] 2023-08-28 23:06
Tmdb key didn't exist in 3.0.15. Refer to my previous points for troubleshooting

**Comment by mrjvs** [comment] 2023-08-28 23:09
Also, configuration is also cached. So make sure you reset your browser cache every change you try

**Comment by ClassickTech** [comment] 2023-08-28 23:15
Wait what? It definitely does have tmdb key.  3.0.15 didn't work for me until I put my own tmdb key, because it came with a default one. My 3.0.15 config.js:

window.__CONFIG__ = {
  // url must NOT end with a slash
  VITE_CORS_PROXY_URL: "https://my.page.com",
  VITE_TMDB_API_KEY: "1234567891011234567890",
  VITE_OMDB_API_KEY: "12345678",
};

My 3.2.1 config is:
window.__CONFIG__ = {
  // url must NOT end with a slash
  VITE_CORS_PROXY_URL: "https://my.page.com",
  VITE_TMDB_READ_API_KEY: "1234567891011234567890"
};

(All fake credentials)

**Comment by castdrian** [comment] 2023-08-28 23:17
did you consider it DOESN'T because you didn't READ and use the correct KEY

**Comment by castdrian** [comment] 2023-08-28 23:18
(also please lock this madness)

**Comment by ClassickTech** [comment] 2023-08-28 23:18
The self host read.me says to get key from here: https://www.themoviedb.org/settings/api. That's teh EXACT same key I am using

**Comment by mrjvs** [comment] 2023-08-28 23:26
3.0.15 never used the tmdb api key. The key type changed from normal to the read only key.

3.1.0 was the first to introduce tmdb media lookup.

To double check if your tmdb key is correct if it allows you to search. If you get any search results at all in your instance, tmdb is configured correctly.

If no sources work but you can search, it has to be the cloudflare worker.

I'm still not confident this is a bug, I'm locking the thread
