### ISSUE TITLE
[Feature]: Add auto play for tv series

### ISSUE THREAD

**Issue by AK-156** [movie-web/movie-web#650] opened 2023-12-30 00:51 UTC
### What feature do you want to add?

add auto play to the on screen ui so you can toggle on or off so you dont have to go and choose the next episode.

### Why do you want to have this feature?

possibly just a tab on/off switch in the episodes menu

**Comment by lonelil** [comment] 2023-12-30 01:02
there’s already a next episode button?

**Comment by castdrian** [comment] 2023-12-30 09:19
duplicate https://github.com/movie-web/movie-web/issues/140

**Comment by GoldenAngel2** [comment] 2023-12-31 01:50
> there’s already a next episode button?

@lonelil I think they're asking for the site to automatically go to the next episode and start playing, instead of having to click the `Next Episode` button every time (which wouldn't be a duplicate of #140 since the site doesn't support the feature currently and what was added for #140 doesn't suit this feature request imo)

**Comment by binaryoverload** [comment] 2024-01-06 12:20
If we add this feature, it would have to be with #581 (Browser Extension) due to otherwise being a much increased load on our proxies

**Comment by JorrinKievit** [comment] 2024-03-25 13:49
^ I would say add this only for extension users

**Comment by TecEash1** [comment] 2024-03-25 14:51
maybe if it’s added it could also be added as a toggelable env (Boolean value - with the default being false) for self holsters? Just because they don’t really have to worry about costs generally

**Comment by quote-therizzler** [comment] 2024-03-25 18:24
^ option for selfhosters would be great

**Closed** 2024-04-14 20:44 UTC
Labels: feature, approved, repo-main, repo-extension
