### ISSUE TITLE
[Bug]: Can't see the movie UI in Windows

### ISSUE THREAD

**Issue by zaim-abbasi** [movie-web/movie-web#658] opened 2023-12-30 11:07 UTC
### What happened?

I can't see the movie UI while playing the movie on my laptop. No options, etc., are displayed. The UI Is working perfectly on my Android device , but not on my windows laptop.
![Screenshot 2023-12-30 160454](https://github.com/movie-web/movie-web/assets/125147306/4e4a30af-db97-4969-9c08-c0e375ed8e55)
![Screenshot 2023-12-30 160612](https://github.com/movie-web/movie-web/assets/125147306/4cb9ff8d-8637-4d49-b326-45c4fb2ded33)

### What browsers are you seeing the problem on?

Chrome

**Comment by Abhishek-200** [comment] 2023-12-30 14:51
The UI is working fine on my end. Have you tried reloading the page? That might help resolve the issue.

**Comment by JipFr** [comment] 2023-12-30 14:52
What browser are you using? It looks like you're also missing some other strings. Do you have any extensions that might be messing with the platform?

**Comment by zaim-abbasi** [comment] 2023-12-30 15:16
Yes, you were right! The issue was due to an extension.

I disabled my extensions one by one and found that a Dark Mode extension was causing the problem. Interestingly, turning it off through its icon didn't work, but disabling it through Chrome extension settings solved the issue. Thanks for your assistance!

**Comment by mrjvs** [comment] 2023-12-30 15:17
Glad its resolved, closing as not a bug

**Closed by mrjvs** 2023-12-30 15:17 UTC
Labels: bug, awaiting-approval
