### ISSUE TITLE
[Feature]: Dual Audio/ Audio Track

### ISSUE THREAD

**Issue by indevatoz** [movie-web/movie-web#919] opened 2024-02-17 14:20 UTC
### What feature do you want to add?

Audio Track/ Dual Audio to choose from, which has multiple audios if available for that movie or tv

### Why do you want to have this feature?

It will be very much useful when watching it on the native or their local language

### Any other details to share?

Just a visual suggestion!
![just a suggestion](https://github.com/movie-web/movie-web/assets/160331404/0a3a25fd-08b8-49c8-a3ae-304f9f9ff09f)

**Comment by JorrinKievit** [comment] 2024-02-17 14:25
Duplicate of #423

**Closed by JorrinKievit** 2024-02-17 14:25 UTC
Labels: feature, awaiting-approval
