### ISSUE TITLE
[Feature]:  Support Other Movie Languages

### ISSUE THREAD

**Issue by tsuki-kami-studios** [movie-web/movie-web#728] opened 2024-01-06 14:02 UTC
### What feature do you want to add?

A selection to get Movies in other languages (for example only in german)

### Why do you want to have this feature?

Couse i want to get german Movies

**Comment by binaryoverload** [comment] 2024-01-06 14:05
Duplicate of #423

**Closed by binaryoverload** 2024-01-06 14:05 UTC
Labels: feature, awaiting-approval

**Comment by tsuki-kami-studios** [comment] 2024-01-06 14:07
Im not sure if its a duplicate, couse the other one wants to change it, but i just want to find it at first.
In my point of view i wouldnt count it as duplicate of the other one.

**Comment by binaryoverload** [comment] 2024-01-06 14:09
> Im not sure if its a duplicate, couse the other one wants to change it, but i just want to find it at first. In my point of view i wouldnt count it as duplicate of the other one.

Finding media outside of changing audio track is a case of suggesting providers - if there are any specific providers then you're welcome to suggest those.
