### ISSUE TITLE
[Feature]: Add online subtitle search to the player

### ISSUE THREAD

**Issue by fadullalah** [movie-web/movie-web#1063] opened 2024-03-31 03:35 UTC
### What feature do you want to add?

It would be great to have the ability to search for subtitles directly from online within the media player. This would streamline the process of finding and adding subtitles for videos, enhancing the overall user experience.

### Why do you want to have this feature?

like the normal subtitle taps

**Comment by zisra** [comment] 2024-03-31 04:02
Duplicate of #124

**Closed** 2024-03-31 14:31 UTC
Labels: feature, awaiting-approval
