### ISSUE TITLE
[Bug]: Subtitles not visible in fullscreen mode on iOS

### ISSUE THREAD

**Issue by en1gma713** [movie-web/movie-web#385] opened 2023-07-15 01:31 UTC
### What happened?

Subtitles are visible when not in fullscreen mode, but when entering fullscreen mode it uses the iOS video player and subtitles disappear. This issue is present in both Safari and Firefox for iOS.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Open movie-web in either Safari or Firefox on iOS
2. Turn on captions
3. Enter fullscreen mode

**Comment by mrjvs** [comment] 2023-07-15 08:15
Duplicate of #336. Closing

**Closed** 2023-07-15 08:15 UTC
Labels: bug, awaiting-approval
