### ISSUE TITLE
[Bug]: Extension version is too old . 

### ISSUE THREAD

**Issue by OdymarGamer** [movie-web/movie-web#960] opened 2024-03-01 12:03 UTC
### What happened?

Extension version is too old  error when doing setup . Its already updated .  

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

download extension and do setup .

**Comment by JorrinKievit** [comment] 2024-03-01 12:10
Duplicate of #957

**Closed by JorrinKievit** 2024-03-01 12:10 UTC
Labels: bug, awaiting-approval
