### ISSUE TITLE
[Bug]: v3.1.0 self-host ZIP possibly broken

### ISSUE THREAD

**Issue by dgw** [movie-web/movie-web#362] opened 2023-06-23 00:40 UTC
### What happened?

I have a self-hosted instance of movie-web v3.0.15 that's been working perfectly for a month. Seeing the release of v3.1.0 today, I decided to upgrade it. This appeared to break two things:

- My "Continue watching" on the homepage disappeared
- Searching for media no longer works (always "Failed to find media, try again!" error)

In that state, movie-web was clearly unusable. I reverted to my previous deploy of v3.0.15 and continued to test locally.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Steps to reproduce?

1. Downloaded the .zip from Releases
2. Copied my proxy URL into `config.js`
3. Dragged-and-dropped the `movie-web` folder to Netlify to deploy it, just like the previous version

I have also confirmed that `cd ~/path/to/3.0.15/movie-web; npx http-server` works perfectly fine, even on localhost; and `cd ~/path/to/3.1.0/movie-web; npx http-server` displays exactly the same symptoms as my Netlify instance.

v3.1.0 was tested on localhost three times:

- .zip extracted with 7-zip
- .zip extracted with `unzip` in terminal
- fresh .zip redownloaded from GitHub and extracted with `unzip`

The symptoms were the same in all three cases.

### Other relevant information

In fact, I went so far as to make sure I had Node v16 installed locally and try the development mode (after creating `.env` and placing my own proxy URL in it—the same one happily serving my v3.0.15 instance).

The same search error appears when run under `yarn dev`. Unfortunately I can't test whether "Continue watching" works properly after upgrade on dev instances that didn't exist before 20 minutes ago.

However, I did find that 70852773f94c30ab47d9737bff8a9875f514c564 is the last commit in which search works properly, in my localhost tests using `git bisect`. (There are some errors in the console, presumably related to the incomplete refactor, but search results still load despite them.) Take my bisect results with a grain of salt, though: I was not able to test revisions that failed to load with a "Misconfigured instance" error related to a missing `TRAKT_CLIENT_ID`.

Given that the main instance appears to be running v3.1.0 just fine, I don't know where to go from here. I can't replicate that deployment exactly, so all I can test are the self-hosted release .zip and `yarn dev` runs. (Hopefully this report at least qualifies as more than asking for "support on how to selfhost", as is _verboten_ in the self-hosting how-to… I was going to just try again after the next release, but then I started testing locally and decided this looks enough like a potential real problem to raise an issue.)

**Comment by castdrian** [comment] 2023-06-23 02:05
not a bug, you blindly jumped from a patch to a minor without performing necessary migrations for breaking such as api keys.

**Comment by dgw** [comment] 2023-06-23 04:40
> you blindly jumped from a patch to a minor without performing necessary migrations for breaking changes such as api keys.

That does not explain why a fresh local clone also fails to search for titles in exactly the same way. I had never cloned the source before today, nor tested any instance on localhost.

In local `yarn dev` testing, I _started_ with the most recent commit to the `dev` branch, which was broken out of the box. Surely there's no way a migration could be skipped in that case? There was no preexisting config or LocalStorage data to migrate.

Honestly, if it was just losing "Currently watching", I'd just live with it and rebuild the list as I continue watching shows. It's the breakage of search, too, that led me to test any local copies in the first place.

If there are migrations that need to be performed manually, I would love to know where the documentation for that lives so I can follow it. movie-web's releases have no release notes or changelogs that I can see, so if there is an option other than "blindly" jumping from one release to the next, I'm unable to find it.

The `config.js` included in the release zipfile is identical between 3.0.15 and 3.1.0, so if those API keys need to be updated, I have no way of knowing that just from following the (otherwise very helpful!) instructions. It seemed highly unlikely to be a true bug, since the main instance appears to work just fine—but if it's not a bug, then there must be a disconnect somewhere in the documentation or sample config provided that no longer matches reality.

**Comment by castdrian** [comment] 2023-06-23 04:42
end users are unaffected, since the migrations happened on the production deployment, as stated in the readme there is no official support for self hosting, furthermore when jumping from a patch to a minor or a major one should always expect breaking changes in one way or another since that is how semver works

**Comment by castdrian** [comment] 2023-06-23 04:46
@dgw if you check the console, you will very clearly see that you are using an invalid tmdb api key, which is what should have been your first step to troubleshoot anyway

**Comment by dgw** [comment] 2023-06-23 05:11
movie-web is a very nice webapp, and I would like to keep using it. If that means going and getting my own API keys (`example.env` still says, "the keys below are optional - defaults are provided"), I'm happy to do so. Just please _document that_ if it's now the case.

I'm not actually frustrated that something _broke_. I'm frustrated that there seems to be absolutely no way I could have prepared for this change because there are no release notes, even when there are (as you say) breaking changes.

If I submitted a pull request that updates the `example.env`, `config.js`, and `SELFHOSTING.md` files to note that self-hosters must now provide their own TMDB API Read Access Token instead of using a default API key that was previously shipped with the zipfile, would you consider the patch? I'm happy to do that.

**Comment by castdrian** [comment] 2023-06-23 05:53
can't speak on that, boss will see and comment eventually, it's still very early in the morning so give it a couple hours

**Comment by mrjvs** [comment] 2023-06-23 06:39
I'll reply in more detail later. Just here for some quick fixes: The tmdb key that was default stopped working, you'll need to add your own readonly key.

After doing that, you can open dev tools and look for local storage. Copy paste the data from `BACKUP-blah` into the non backup versions. This will restore your lost data.

**Comment by dgw** [comment] 2023-06-23 07:04
> The tmdb key that was default stopped working, you'll need to add your own readonly key.

Yep, eventually figured out that not only the key but the key _type_ had changed.

My offer to open a PR with the necessary edits in documentation and sample config/env files still stands; just ping me later today/tomorrow. Shouldn't take me long. 🙂

> you can open dev tools and look for local storage. Copy paste the data from `BACKUP-blah` into the non backup versions. This will restore your lost data.

Thanks for this. Since I already use Trakt's progress page to figure out what to watch next I won't worry too much about chasing down why a few of the `video-progress` entries aren't migrated to the new `--version`. It's good enough!

**Comment by mrjvs** [comment] 2023-06-23 07:36
Ok so, I read the entire thread and got some time to formulate a reply :)
I disagree with @castdrian, I think all of this is something we should improve on our end.

First I'd like to apologise, we made a breaking change with 0 way to tell what changed for selfhosters, and it deleting all locally stored data on top of that. It's not how I would've liked it to go, and I certainly understand your frustrations there. I would also be frustrated if I were in your position.

We should've documented how to upgrade from 3.0.15, and also it shouldn't have deleted the data when a config item was missing.

In the future, we'll be documenting upgrade paths when a breaking change is made. but also prevent the possibility for someone to miss it: if someone doesn't follow the upgrade path, it should display an error of some kind instead of just rolling with it.

Version 3.1 is the last update for version 3, we're moving into version 4 now. I'll be sure to make the upgrade from 3 to 4 painless. That includes a better selfhosting guide as well. So no need for you to make a PR, thanks for the offer though.

Later today, I will be updating the release notes with how to add a TMBD key and update the selfhosting guide to reflect the new key as well.

This is the first time we've had breaking changes since we made the selfhosting guide, a good lesson for the future on how to handle these things.

Hope that answer satisfies.

**Comment by dgw** [comment] 2023-06-23 07:46
It sounds like a great plan! Thanks for laying it all out.

I'll have a look at the documentation update next time I check the repo, and keep an eye out for any gotchas the v4 update might bring when it's ready. I really appreciate all the work y'all are doing on this app; my best wishes to the whole team. ✌️

**Comment by mrjvs** [comment] 2023-06-23 20:23
Right, I've done the following:
1. The selfhosting guide has been updated with updated info on how to populate config.js.
It doesn't have an upgrade guide per se, but you can just follow the steps again and skip what you've already done. (only one step was added for the TMDB key).

2. The web page now double checks if all of the configuration is in place before it tries doing anything. So no data would be cleared as a result of bad configuration. It also makes it easier to spot when configuration needs to be changed, as it just says "Misconfigured instance: Missing key ..." and then shows an error page.

3. Version 3.1.0 has been removed as a github release, as its superseded by the more safe v3.1.1.

Im gonna close this issue as resolved, but if there any more questions about any of this, let me know.

**Closed by mrjvs** 2023-06-23 20:23 UTC
Labels: bug

**Comment by dgw** [comment] 2023-06-23 20:55
Had a look at the new release, and the updated instructions look great!

One thing: There is a mismatch now between the instructions and the `config.js` template shipped in the zip. Based on

https://github.com/movie-web/movie-web/blob/00e25f1ae41a0e0f2d03c6c3484859dc0ec16c01/src/setup/config.ts#L21-L22

the template line here should be prefixed with `VITE_`:

https://github.com/movie-web/movie-web/blob/00e25f1ae41a0e0f2d03c6c3484859dc0ec16c01/public/config.js#L4

Since the instructions are updated, other self-hosters like me should be able to figure this one out until whenever the next patch release comes—and if they don't, the webapp's improved error handling should point them toward the problem.

I've updated my deployment (including the `VITE_` prefix mentioned above), and also had 100% success with re-restoring my `BACKUP-v2-video-progress` localstorage data on v3.1.1 🥳

Thanks for getting this sorted so quickly!

**Comment by mrjvs** [comment] 2023-06-23 21:09
Thanks for letting me know.
There is now a v3.1.2 with an updated config.js and the selfhosting guide also has the typo fixed.
No actual code changes besides the preset config.js

**Comment by adhrn** [comment] 2023-10-07 01:55
i get a Failed to find media, try again! msg

**Comment by adhrn** [comment] 2023-10-07 01:56
should my cloudflare works page say "200 ok"?

**Comment by dgw** [comment] 2023-10-07 02:21
> should my cloudflare works page say "200 ok"?

Mine does.

Please don't hijack old issues.

**Comment by binaryoverload** [comment] 2023-10-07 15:46
> > should my cloudflare works page say "200 ok"?
> 
> Mine does.
> 
> Please don't hijack old issues. This is about v3.1.0, and movie-web is now at v3.2.1.

Agreed - we also don't provide support for self-hosting outside of actual issues with our code @adhrn
