### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by divmagic** [movie-web/movie-web#548] opened 2023-12-16 22:10 UTC
### What happened?

```superstream: notfound Couldn't find a stream: No entry found zoechip: pending gomovies: failure TypeError: Failed to fetch flixhq: failure TypeError: Failed to fetch remotestream: failure TypeError: Failed to fetch zoechip-0: failure TypeError: Failed to fetch zoechip-1: failure TypeError: Failed to fetch ```

**Comment by akumaaayush** [comment] 2023-12-16 22:14
Duplicate of #545

**Closed** 2023-12-17 00:26 UTC
Labels: bug, awaiting-approval
