### ISSUE TITLE
[Feature]: Providing a way for friends to watch movies together with single player and microphone support

### ISSUE THREAD

**Issue by shehryardev** [movie-web/movie-web#795] opened 2024-01-19 19:31 UTC
### What feature do you want to add?

A cozy feature for friends to stream and watch movies in sync, no matter where they are. It's like a virtual movie night with a single player that everyone can see. Plus, there's a microphone option so you all can chat, laugh, and comment in real-time, making movie nights lively and interactive, just like old times.

### Why do you want to have this feature?

This feature bridges distances, allowing friends to share movie experiences together online. It fosters social connections and brings the fun of a movie night into everyone's living room, no matter where they are.

**Comment by JorrinKievit** [comment] 2024-01-19 19:38
Duplicate of #109 😊

**Closed by JorrinKievit** 2024-01-19 19:37 UTC
Labels: feature, awaiting-approval
