### ISSUE TITLE
[Bug]: "Check your internet connection" warning when there's no internet connection issue.

### ISSUE THREAD

**Issue by Drunkenrailer** [movie-web/movie-web#966] opened 2024-03-02 11:34 UTC
### What happened?

There's a red warning bar at the top of the screen that doesn't go away when watching in full-screen.
![image_2024-03-02_063320068](https://github.com/movie-web/movie-web/assets/93374568/53196de4-d919-47c4-8a24-e793813bd196)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

Using opera GX

**Comment by JorrinKievit** [comment] 2024-03-02 11:39
Duplicate of #945 , check pinned issue

**Closed by JorrinKievit** 2024-03-02 11:39 UTC
Labels: bug, awaiting-approval
