### ISSUE TITLE
[Feature]: Request for cross device sync

### ISSUE THREAD

**Issue by gsriram24** [movie-web/movie-web#477] opened 2023-11-04 12:15 UTC
### What feature do you want to add?

Requesting for a cross device sync with authentication, so that the last played episode and recents are synced across multiple devices. 

### Why do you want to have this feature?

A good experience to view shows/movies across multiple devices.

**Comment by mrjvs** [comment] 2023-11-04 12:20
duplicate of #344

**Closed by mrjvs** 2023-11-04 12:20 UTC
Labels: feature, awaiting-approval
