### ISSUE TITLE
[Feature]: Feature to change the aspect ratio of videos

### ISSUE THREAD

**Issue by tejas-mn** [movie-web/movie-web#800] opened 2024-01-21 05:32 UTC
### What feature do you want to add?

Feature to change the aspect ratio of videos.

### Why do you want to have this feature?

Feature to change the aspect ratio of videos to fit the device screen sizes since different sources/videos have different aspect ratios.

**Comment by zisra** [comment] 2024-01-21 20:32
Duplicate of #425

**Closed** 2024-01-21 20:37 UTC
Labels: feature, awaiting-approval
