### ISSUE TITLE
[Feature]: Add an age-rated tag on movies and shows.

### ISSUE THREAD

**Issue by itsmeadarsh2008** [movie-web/movie-web#1126] opened 2024-04-16 03:45 UTC
### What feature do you want to add?

A rated tag for movies and shows that tells about the suitable ages to watch and the filter options to search movies.

### Why do you want to have this feature?

If I'm ever to watch with my family, I can categorise what to watch.

### Any other details to share?

None

**Comment by JorrinKievit** [comment] 2024-04-16 04:59
TMDB does not have that kind of data

**Comment by zisra** [comment] 2024-04-16 05:17
It does, actually 

https://developer.themoviedb.org/reference/tv-series-content-ratings

**Comment by itsmeadarsh2008** [comment] 2024-04-16 05:50
Someone please open this issue again.

**Comment by itsmeadarsh2008** [comment] 2024-04-16 09:37
Are you shipping this with version 5? I don't think it's going take that much long for that.

**Comment by castdrian** [comment] 2024-04-16 15:10
The issue is not approved as of yet and certainly no one is gonna feel inclined to approve it or work on it if you keep pestering people.

**Comment by binaryoverload** [comment] 2024-04-20 10:10
As far as I can see, the age rating endpoints for [movies](https://developer.themoviedb.org/reference/movie-release-dates) and [TV shows](https://developer.themoviedb.org/reference/tv-series-content-ratings) are only available for when we request data for a single media; we can't access that data in the search.

As such, we wouldn't be able to filter/tag shows in the search results without requesting each media item which would add a big request overhead to the search page. 

There is also the complexity of parsing the age ratings and determining which ones to use, as each country has different ones!

I don't think we should do this if we can't get the data when searching. We already filter out shows that TMDB marks as "adult".

@movie-web/project-leads do you concur?

**Comment by JorrinKievit** [comment] 2024-04-20 10:34
Me neither, the adult filter seems sufficient enough 👍, closing

**Closed by JorrinKievit** 2024-04-20 10:34 UTC
Labels: feature, awaiting-approval
