### ISSUE TITLE
[Bug]: Fetching bad formatted captions

### ISSUE THREAD

**Issue by mordisk10** [movie-web/movie-web#445] opened 2023-09-25 19:04 UTC
### What happened?

If you set your captions to turkish and test it you will end up with pretty bad unreadable captions.

- it may be not just a language specific issue not only turkish
- tried with multiple devices and browsers
- it happens with the letters: ''ğ 'ı' 'ş'
- these are just fine: 'ü' 'ç'

### What browsers are you seeing the problem on?

Firefox, Chrome

### Steps to reproduce?

1. type rick and morty for example
2. start watching the S1 E1
3. set captions language to Turkish
4. in the attached image it says "Gecenin bir yarýsý" but it should be "Gecenin bir yarısı"

### Other relevant information

![image](https://github.com/movie-web/movie-web/assets/70017374/4255d417-30b8-43b5-9223-7a3f7e448fb5)
![image](https://github.com/movie-web/movie-web/assets/70017374/55d7cb84-7115-4843-a05a-67c390888878)

**Comment by zisra** [comment] 2023-09-25 20:22
Possible duplicate of #237

**Comment by mordisk10** [comment] 2023-09-25 20:24
an ugly fix for this problem someone can find a better solution
```typescript
export function parseSubtitles(text: string): ContentCaption[] {
  let textTrimmed = text.trim();
  if (textTrimmed === "") {
    throw new Error("Given text is empty");
  }
  if (detect(textTrimmed) === "") {
    throw new Error("Invalid subtitle format");
  }
  // TODO check if the subtitle is in Turkish if so, replace them with their correct forms
  textTrimmed = textTrimmed
    .replaceAll("ý", "ı")
    .replaceAll("Ý", "İ")
    .replaceAll("þ", "ş")
    .replaceAll("ð", "ğ");
  return parse(textTrimmed).filter(
    (cue) => cue.type === "caption"
  ) as ContentCaption[];
}
```

**Comment by binaryoverload** [comment] 2023-10-09 16:38
Duplicate of https://github.com/movie-web/movie-web/issues/387

**Closed by binaryoverload** 2023-10-09 16:38 UTC
Labels: bug, awaiting-approval
