### ISSUE TITLE
[Feature]: Watch party feature

### ISSUE THREAD

**Issue by piyush-panpaliya** [movie-web/movie-web#388] opened 2023-07-26 16:50 UTC
### What feature do you want to add?

ability to watch a movie with other users in sync, p2p stuff can be done to achieve this

### Why do you want to have this feature?

its an important feature of any media app

**Comment by lem6ns** [comment] 2023-07-26 16:51
dupe of #109 !!

**Closed** 2023-07-26 17:00 UTC
Labels: feature, awaiting-approval
