### ISSUE TITLE
[Feature]: Movie/series details 

### ISSUE THREAD

**Issue by russssl** [movie-web/movie-web#765] opened 2024-01-09 22:53 UTC
### What feature do you want to add?

 Create An ability to get all of the movie details (e.g. cast crew rating description etc.) so it can be viewed inside the app. 

### Why do you want to have this feature?

it would be cool to have detailed info about a movie I am watching. Currently, I have started to make front-end changes required for this feature, but I can go only to a certain level without touching on the backend section of it. More specific requirements I will add after the response

**Comment by zisra** [comment] 2024-01-09 23:00
Duplicate #334

**Comment by russssl** [comment] 2024-01-09 23:02
@zisra so is this being implemented or it was dropped ?

**Comment by zisra** [comment] 2024-01-09 23:03
I can't mention it 🙈

**Comment by binaryoverload** [comment] 2024-01-09 23:05
Duplicate of #334

**Comment by russssl** [comment] 2024-01-09 23:05
@zisra I see you mentioned duplicate, as I understood idea exists, but has the back end for this has been done in some level or this is to be done ? As I said I can't make all of the front without having back at some point

**Closed by binaryoverload** 2024-01-09 23:05 UTC
Labels: feature, awaiting-approval

**Comment by russssl** [comment] 2024-01-09 23:09
@zisra so details are already present at the front end ? Like directors cast and stuff? Maybe we get this info when we click the show ? Sorry I do not know what info those api calls to tmdb return

**Comment by zisra** [comment] 2024-01-09 23:11
@russssl TMDB returns all the appropriate data, although you would probably need to use the `append_to_response` parameter to add some extra information. All the documentation is [here](https://developer.themoviedb.org/reference/movie-details)

**Comment by russssl** [comment] 2024-01-09 23:11
If it is the case I will use the old details screen concept as an example:)

**Comment by mrjvs** [comment] 2024-01-09 23:11
Keep in mind the issue is not approved, so it will not be merged if you make a pull request

**Comment by russssl** [comment] 2024-01-09 23:13
@mrjvs I do understand that but I think pr should be approved at some point (or so I hope:))

**Comment by russssl** [comment] 2024-01-09 23:34
@mrjvs and what is the criteria for the issue to be approved

**Comment by mrjvs** [comment] 2024-01-09 23:35
We need to agree with the idea, we don't currently think we should add this feature

**Comment by russssl** [comment] 2024-01-09 23:37
Well that's unfortunate. As I said I will code it anyways because this idea is quite appealing to me, but if you say so, be it. I hope someday I will see it merged into the main repo
