### ISSUE TITLE
[Feature]:  Change video resolution

### ISSUE THREAD

**Issue by PyCoder158** [movie-web/movie-web#430] opened 2023-09-07 20:35 UTC
### What feature do you want to add?

Change resolution option for streaming/downloading

### Why do you want to have this feature?

Option to change resolution for less bandwidth/smaller download size

**Comment by castdrian** [comment] 2023-09-07 20:36
duplicate of https://github.com/movie-web/movie-web/issues/318

**Closed** 2023-09-07 20:37 UTC
Labels: feature, awaiting-approval
