### ISSUE TITLE
[Bug]: Error while finding videos in VidSrc: We encountered an error! Error: invalid source id 

### ISSUE THREAD

**Issue by RazyAnas** [movie-web/movie-web#773] opened 2024-01-11 14:56 UTC
### What happened?

![Screenshot from 2024-01-11 20-22-43](https://github.com/movie-web/movie-web/assets/59137612/7d4d63a8-dba5-4f46-92db-be59b66b7330)
![Screenshot from 2024-01-11 20-22-04](https://github.com/movie-web/movie-web/assets/59137612/21abf23a-e3c8-4591-98d3-29dd2494b624)
Sometimes it overcomes when reloaded, most of the times it dont. the error persist. example movie query: "rocky aur rani ki prem kahani"

### Steps to reproduce?

1. Searched for movie: Dunki, rocky aur rani ki prem kahani, 12th fail (when reloaded, error disappeared), bawaal 2023, etc
2. while it was searching for movies in VidSrc the error was ejected. 

### Other relevant information

The provider VidSrc has errors.

**Comment by blikje7up** [comment] 2024-01-11 14:57
duplicate of https://github.com/movie-web/movie-web/issues/770

**Closed** 2024-01-11 18:16 UTC
Labels: bug, awaiting-approval
