### ISSUE TITLE
[Feature]: Source order / priority customisation

### ISSUE THREAD

**Issue by Ciarands** [movie-web/movie-web#848] opened 2024-01-28 07:59 UTC
### What feature do you want to add?

A way to change what order sources are scraped in or simply to set a preferred default source which is always scraped first, similar to how you can set a default language for subtitles.

### Why do you want to have this feature?

After watching a show, I've noticed that the quality hasn't been great on LookMovie, however it seems to be fine on the other sources.
As LookMovie has this title it will always be scraped first, meaning each time you have to manually change the source. 
Obviously not a huge issue, but it would be a nice QoL feature to be able to manipulate what order sources are scraped in, so that the user doesn't have to manually change the source each time.

### Anything other details to share?

N/A

**Comment by zisra** [comment] 2024-01-28 16:09
Duplicate of #714

**Closed** 2024-01-28 19:58 UTC
Labels: feature, awaiting-approval
