### ISSUE TITLE
[Feature]: Select preferrred video source

### ISSUE THREAD

**Issue by roxxel** [movie-web/movie-web#852] opened 2024-01-29 20:19 UTC
### What feature do you want to add?

A setting to select preferred video source

### Why do you want to have this feature?

Some of the video sources perform poorly in my region (loading time). I'm sure this happened to others too

**Comment by blikje7up** [comment] 2024-01-29 20:25
duplicate of https://github.com/movie-web/movie-web/issues/714

**Closed** 2024-01-29 20:33 UTC
Labels: feature, awaiting-approval
