### ISSUE TITLE
[Bug]:  PiP button is shown, requesting it throws error on mobile

### ISSUE THREAD

**Issue by frost768** [movie-web/movie-web#197] opened 2023-03-11 10:49 UTC
### What happened?

Requesting PiP on mobile throws the following error even though `document.pictureInPictureEnabled` returns true.
`Error: Failed to execute 'requestPictureInPicture' on 'HTMLVideoElement': Picture-in-Picture is not available.`

Expected behaviour
Video being in PiP mode or not seeing the button

### What browsers are you seeing the problem on?

Chrome, Other (tell us in input box below)

### Steps to reproduce?

1. Open Brave or Chrome on Android
2. Go to any movie or series ([example](https://movie-web.app/media/JW-movie-439596))
3. Tap PiP button
4. Nothing happens

**Comment by mrjvs** [comment] 2023-03-11 13:18
doesnt happen for me on android chrome, but we should just catch the request errors, its probably fine if we catch and then ignore the error.

**Comment by frost768** [comment] 2023-03-11 14:03
I guess it's related to my phone. Tried other browsers every one of them gives the same result

**Comment by mrjvs** [comment] 2023-06-16 17:46
closing for now, needs global reproduction. cannot reproduce myself with instructions

**Closed by mrjvs** 2023-06-16 17:46 UTC
Labels: bug, bug:needs-reproduction
