### ISSUE TITLE
[Bug]: Playback error doesn't disappear after switching providers

### ISSUE THREAD

**Issue by ari-party** [movie-web/movie-web#739] opened 2024-01-06 16:43 UTC
### What happened?

Provider failed because e.g. hls error
Switch provider, audio plays and stops after a few seconds but the playback error never went away.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

^ Vivaldi

**Comment by JorrinKievit** [comment] 2024-03-03 20:07
Duplicate of #712

**Closed by JorrinKievit** 2024-03-03 20:07 UTC
Labels: bug, approved
