### ISSUE TITLE
[Bug]: The Scrub bar circle sometimes is low quality

### ISSUE THREAD

**Issue by ooosssay** [movie-web/movie-web#251] opened 2023-04-06 02:25 UTC
### What happened?

The scrub bar circle when watching a video would sometimes be pixelated.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

1) Start the video
2) Scrub through the scrub bar
3) The scrub bar circle being low quality

### Other relevant information

![IMG_5008](https://user-images.githubusercontent.com/129241633/230256590-5e540af8-a6a4-4537-b77f-182ac58dff54.jpeg)

**Comment by zisra** [comment] 2023-04-06 02:27
Cannot reproduce, what type of device are you using @ooosssay ?

**Comment by ooosssay** [comment] 2023-04-06 02:42
iPad. @zisra

**Comment by mrjvs** [comment] 2023-06-16 18:04
cannot reproduce, closing

**Comment by mrjvs** [comment] 2023-06-16 19:55
> Can reproduce on iPad

added for investigation to v4. if we cant find an easy fix, its considered a browser bug, out of scope

**Comment by binaryoverload** [comment] 2024-03-16 09:56
No complaints about this since, closing

**Closed by binaryoverload** 2024-03-16 09:56 UTC
Labels: bug, approved, repo-main
