### ISSUE TITLE
[Bug]: The hosted version prevents web inspect

### ISSUE THREAD

**Issue by nimagp** [movie-web/movie-web#370] opened 2023-06-26 07:25 UTC
### What happened?

The web page uses debug statements to make the browser crash

### Steps to reproduce?

Open inspect page

### Other relevant information

Why?
What does the alert () with text "Leave us alone :(" mean and how it is displayed if there is no alert() or the string hardcoded into the code present in the repository?

**Comment by zisra** [comment] 2023-06-26 07:31
Not a bug, see #264

**Comment by mrjvs** [comment] 2023-06-26 07:39
like @zisra said, not a bug. check my comment on the issue they linked. Closing.

**Closed by mrjvs** 2023-06-26 07:39 UTC
Labels: bug
