### ISSUE TITLE
[Bug]: Download on deskctop browser gives RangeError

### ISSUE THREAD

**Issue by ast4897** [movie-web/movie-web#798] opened 2024-01-19 23:16 UTC
### What happened?

When I click on download, it says RangeError: Maximum call stack size exceeded

![image](https://github.com/movie-web/movie-web/assets/65278022/9e597337-0089-4a10-9202-68af0b9c51cf)

**Comment by zisra** [comment] 2024-01-22 21:12
Duplicate of #589

**Closed** 2024-01-22 21:14 UTC
Labels: bug, awaiting-approval
