### ISSUE TITLE
[Bug]: Turkish/Special Characters Don't Show Correctly

### ISSUE THREAD

**Issue by eggsy** [movie-web/movie-web#743] opened 2024-01-06 23:07 UTC
### What happened?

In all of the movies with automatic Turkish subtitles detection, they fail to load the special characters such as "ş", "ç", "ö", "İ", "ü" and et cetera. I've tried installing a local subtitle file, same thing happened. I think there's a problem with the project's subtitle parsing or website/font missing the required character support. Here's an example from Kingsman: The Golden Circle:

<img width="420" alt="image" src="https://github.com/movie-web/movie-web/assets/13917975/5b1d02e9-8403-42ce-8afe-e3dbb64cc0f5">

You can try downloading an example subtitle [from here](https://turkcealtyazi.org/sub/692481/kingsman-the-golden-circle.html) to see it yourself.

I've checked the .srt file and there's no issue with the characters in this file:

<img width="275" alt="image" src="https://github.com/movie-web/movie-web/assets/13917975/8cc60ac4-b5f1-4d71-ad92-fd1a65f42bde">

### What browsers are you seeing the problem on?

Microsoft Edge

### Steps to reproduce?

1. Download the example .srt file from a website like [turkcealtyazi.org](https://turkcealtyazi.org/).
2. Load from a local source in the movie you want.
3. Check out the special characters.

**Comment by zisra** [comment] 2024-01-07 09:12
Possible duplicate of #387

**Comment by JorrinKievit** [comment] 2024-03-03 20:23
Yep 😄

**Closed by JorrinKievit** 2024-03-03 20:23 UTC
Labels: bug, awaiting-approval
