### ISSUE TITLE
[Bug]: The site is putting a false resolution for what it actually is 

### ISSUE THREAD

**Issue by schoolgadou** [movie-web/movie-web#552] opened 2023-12-17 18:37 UTC
### What happened?

image
It says its 1080p but in reality its only 720 It has been happening ever since I started using movie-web 8 or so months ago maybe a little longer, sometimes it is extremely worse and unwatchable
Could you guys please fix it, Thanks

**Comment by JipFr** [comment] 2023-12-17 18:39
Are you still experiencing this in the new update? I believe we fixed it in yesterday's update

**Comment by schoolgadou** [comment] 2023-12-17 18:43
> Are you still experiencing this in the new update? I believe we fixed it in yesterday's update

I'm seeing it less also could you tell me why even do I have fibre broadband and its still taking forever to load, it's starting to get annoying Do you want to try on the same movie as me? here is the link and tell me if its lagging for you too https://movie-web.app/media/tmdb-tv-81144-the-neighborhood/298434/4272155

**Comment by binaryoverload** [comment] 2023-12-28 20:57
Duplicate of #550

**Closed by binaryoverload** 2023-12-28 20:57 UTC
Labels: bug, awaiting-approval
