### ISSUE TITLE
[Bug]: difficulty changing between episodes on mobile

### ISSUE THREAD

**Issue by 1479sam** [movie-web/movie-web#310] opened 2023-05-26 11:53 UTC
### What happened?

difficulty changing between episodes on mobile, after clicking the next episode it will not change episodes. it will either play the same episode or show it's playing the selected episode but play the previous episode.

### What browsers are you seeing the problem on?

Firefox

### Other relevant information

occurs on firefox for mobile and opera gx for mobile, the series is star trek (tos) but may occur for other series

**Comment by nodlek-ctrl** [comment] 2023-06-13 12:23
Hmm. I have same issue, also firefox mobile. I will take a look when I can.

**Comment by mrjvs** [comment] 2023-06-16 18:23
cannot reproduce, closing

**Closed by mrjvs** 2023-06-16 18:23 UTC
Labels: bug
