### ISSUE TITLE
[Bug]: Video not auto-playing upon selecting the movie/series

### ISSUE THREAD

**Issue by nmotapar** [movie-web/movie-web#398] opened 2023-08-04 16:50 UTC
### What happened?

Video not auto-playing after we select the movie. We have to manually select the play button on the bottom of the player. It'd be nice to have it autoplayed (with subtitles language auto selected from previous selections)

### What browsers are you seeing the problem on?

Safari

**Comment by castdrian** [comment] 2023-08-04 16:52
duplicate of https://github.com/movie-web/movie-web/issues/140

**Closed** 2023-08-04 22:21 UTC
Labels: bug, awaiting-approval
