### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by gbox1** [movie-web/movie-web#449] opened 2023-10-03 15:14 UTC
### What feature do you want to add?

Add Admin Panel

### Why do you want to have this feature?

when a user visit the website they first need to register and login the website and have user profile and admin profile too

**Comment by mrjvs** [comment] 2023-10-03 21:17
admin panel is duplicate of #426

auth guard is currently not in scope.

**Closed by mrjvs** 2023-10-03 21:17 UTC
Labels: feature, awaiting-approval
