### ISSUE TITLE
[Feature]: Skip intro and outro 

### ISSUE THREAD

**Issue by fadullalah** [movie-web/movie-web#1130] opened 2024-04-16 07:17 UTC
### What feature do you want to add?

Add the skip intro and outro feature to the player

### Why do you want to have this feature?

It will make the player more unique and easy to use

### Any other details to share?

Thank you

**Comment by JorrinKievit** [comment] 2024-04-16 07:46
Duplicate of #347

**Closed by JorrinKievit** 2024-04-16 07:46 UTC
Labels: feature, awaiting-approval
