### ISSUE TITLE
[Feature]: Create a Recommendation System

### ISSUE THREAD

**Issue by sasankaweera123** [movie-web/movie-web#395] opened 2023-08-01 13:41 UTC
### What feature do you want to add?

Add a Recommendation System

### Why do you want to have this feature?

- It will be easier for go with update movies 
- Can attract more users

**Comment by mrjvs** [comment] 2023-08-01 22:04
somewhat a duplicate of #311, closing for same reasons

**Closed by mrjvs** 2023-08-01 22:04 UTC
Labels: feature, awaiting-approval
