### ISSUE TITLE
[Bug]: Subtitles not showing up in iPad/iPhone full screen

### ISSUE THREAD

**Issue by nmotapar** [movie-web/movie-web#397] opened 2023-08-04 16:46 UTC
### What happened?

When watching in player, subtitles show as expected. But when you click on full sceen, it opens ios/ipad OS video interface and subtitles are not showing up.

### What browsers are you seeing the problem on?

Chrome, Safari

### Steps to reproduce?

1. Play any movie/series in iPad
2. turn on subtitles
3. Go full screen, subtitles won't show

**Comment by castdrian** [comment] 2023-08-04 16:49
duplicate of https://github.com/movie-web/movie-web/issues/336

**Closed** 2023-08-04 22:19 UTC
Labels: bug, awaiting-approval
